# Generated by Django 4.1 on 2022-08-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='municipioAddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMpio', models.CharField(max_length=100)),
                ('idMpio', models.IntegerField()),
                ('idDepto', models.IntegerField()),
                ('consecutivo', models.IntegerField()),
                ('region', models.CharField(max_length=1)),
            ],
        ),
    ]
